--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)
-- Dumped by pg_dump version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE number_guess;
--
-- Name: number_guess; Type: DATABASE; Schema: -; Owner: freecodecamp
--

CREATE DATABASE number_guess WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C.UTF-8' LC_CTYPE = 'C.UTF-8';


ALTER DATABASE number_guess OWNER TO freecodecamp;

\connect number_guess

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: games; Type: TABLE; Schema: public; Owner: freecodecamp
--

CREATE TABLE public.games (
    game_id integer NOT NULL,
    username character varying(22) NOT NULL,
    number_of_guesses integer NOT NULL
);


ALTER TABLE public.games OWNER TO freecodecamp;

--
-- Name: games_game_id_seq; Type: SEQUENCE; Schema: public; Owner: freecodecamp
--

ALTER TABLE public.games ALTER COLUMN game_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: games; Type: TABLE DATA; Schema: public; Owner: freecodecamp
--

INSERT INTO public.games VALUES (1, 'Sergo', 8);
INSERT INTO public.games VALUES (2, 'user_1781879503987', 776);
INSERT INTO public.games VALUES (3, 'user_1781879503987', 268);
INSERT INTO public.games VALUES (4, 'user_1781879503986', 673);
INSERT INTO public.games VALUES (5, 'user_1781879503986', 490);
INSERT INTO public.games VALUES (6, 'user_1781879503987', 513);
INSERT INTO public.games VALUES (7, 'user_1781879503987', 363);
INSERT INTO public.games VALUES (8, 'user_1781879503987', 774);
INSERT INTO public.games VALUES (9, 'user_1781879619054', 96);
INSERT INTO public.games VALUES (10, 'user_1781879619054', 688);
INSERT INTO public.games VALUES (11, 'user_1781879619053', 989);
INSERT INTO public.games VALUES (12, 'user_1781879619053', 471);
INSERT INTO public.games VALUES (13, 'user_1781879619054', 450);
INSERT INTO public.games VALUES (14, 'user_1781879619054', 194);
INSERT INTO public.games VALUES (15, 'user_1781879619054', 81);
INSERT INTO public.games VALUES (16, 'user_1781879747138', 881);
INSERT INTO public.games VALUES (17, 'user_1781879747138', 480);
INSERT INTO public.games VALUES (18, 'user_1781879747137', 43);
INSERT INTO public.games VALUES (19, 'user_1781879747137', 409);
INSERT INTO public.games VALUES (20, 'user_1781879747138', 487);
INSERT INTO public.games VALUES (21, 'user_1781879747138', 310);
INSERT INTO public.games VALUES (22, 'user_1781879747138', 737);
INSERT INTO public.games VALUES (23, 'user_1781879780009', 878);
INSERT INTO public.games VALUES (24, 'user_1781879780009', 851);
INSERT INTO public.games VALUES (25, 'user_1781879780008', 157);
INSERT INTO public.games VALUES (26, 'user_1781879780008', 251);
INSERT INTO public.games VALUES (27, 'user_1781879780009', 209);
INSERT INTO public.games VALUES (28, 'user_1781879780009', 951);
INSERT INTO public.games VALUES (29, 'user_1781879780009', 547);
INSERT INTO public.games VALUES (30, 'user_1781879787172', 165);
INSERT INTO public.games VALUES (31, 'user_1781879787172', 1001);
INSERT INTO public.games VALUES (32, 'user_1781879787171', 443);
INSERT INTO public.games VALUES (33, 'user_1781879787171', 495);
INSERT INTO public.games VALUES (34, 'user_1781879787172', 573);
INSERT INTO public.games VALUES (35, 'user_1781879787172', 837);
INSERT INTO public.games VALUES (36, 'user_1781879787172', 797);
INSERT INTO public.games VALUES (37, 'user_1781879793853', 808);
INSERT INTO public.games VALUES (38, 'user_1781879793853', 539);
INSERT INTO public.games VALUES (39, 'user_1781879793852', 179);
INSERT INTO public.games VALUES (40, 'user_1781879793852', 23);
INSERT INTO public.games VALUES (41, 'user_1781879793853', 660);
INSERT INTO public.games VALUES (42, 'user_1781879793853', 187);
INSERT INTO public.games VALUES (43, 'user_1781879793853', 854);
INSERT INTO public.games VALUES (44, 'user_1781879924336', 465);
INSERT INTO public.games VALUES (45, 'user_1781879924336', 483);
INSERT INTO public.games VALUES (46, 'user_1781879924335', 584);
INSERT INTO public.games VALUES (47, 'user_1781879924335', 250);
INSERT INTO public.games VALUES (48, 'user_1781879924336', 556);
INSERT INTO public.games VALUES (49, 'user_1781879924336', 973);
INSERT INTO public.games VALUES (50, 'user_1781879924336', 536);
INSERT INTO public.games VALUES (51, 'user_1781879931072', 776);
INSERT INTO public.games VALUES (52, 'user_1781879931072', 110);
INSERT INTO public.games VALUES (53, 'user_1781879931071', 97);
INSERT INTO public.games VALUES (54, 'user_1781879931071', 87);
INSERT INTO public.games VALUES (55, 'user_1781879931072', 81);
INSERT INTO public.games VALUES (56, 'user_1781879931072', 182);
INSERT INTO public.games VALUES (57, 'user_1781879931072', 794);
INSERT INTO public.games VALUES (58, 'user_1781879957990', 687);
INSERT INTO public.games VALUES (59, 'user_1781879957990', 700);
INSERT INTO public.games VALUES (60, 'user_1781879957989', 738);
INSERT INTO public.games VALUES (61, 'user_1781879957989', 163);
INSERT INTO public.games VALUES (62, 'user_1781879957990', 326);
INSERT INTO public.games VALUES (63, 'user_1781879957990', 869);
INSERT INTO public.games VALUES (64, 'user_1781879957990', 890);
INSERT INTO public.games VALUES (65, 'bob', 10);
INSERT INTO public.games VALUES (66, 'user_1781880050930', 423);
INSERT INTO public.games VALUES (67, 'user_1781880050930', 15);
INSERT INTO public.games VALUES (68, 'user_1781880050929', 658);
INSERT INTO public.games VALUES (69, 'user_1781880050929', 420);
INSERT INTO public.games VALUES (70, 'user_1781880050930', 179);
INSERT INTO public.games VALUES (71, 'user_1781880050930', 332);
INSERT INTO public.games VALUES (72, 'user_1781880050930', 846);


--
-- Name: games_game_id_seq; Type: SEQUENCE SET; Schema: public; Owner: freecodecamp
--

SELECT pg_catalog.setval('public.games_game_id_seq', 72, true);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (game_id);


--
-- PostgreSQL database dump complete
--

